### ISSUE TITLE
Heist completion screen doesn't progress

### ISSUE THREAD

**Issue by gaberenest** [DrNewbie/Overdrill-Stealth#1]
Unsure if intentional or not to prevent "carry stacker speedrunning", but upon finishing the heist, the loot/xp counter will freeze. Other heists unaffected.

**Comment by CyjanekPotasu** [comment]
i know its of the topic but pls help me install it i drop it to the mods folder and nothing happens after getting 1 bag 2 the vent plss help

**Comment by DrNewbie** [comment]
not insetered in it
